[package]
name = "desktop"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "econbox"
path = "src/main.rs"

[dependencies]
bevy = { workspace = true, features = ["2d", "ui"] }
serde = { workspace = true }
econbox = { workspace = true }
econbox-art = { workspace = true }
econbox-brush = { workspace = true }
econbox-camera = { workspace = true }
econbox-clock = { workspace = true }
econbox-creature = { workspace = true }
econbox-cursor = { workspace = true }
econbox-tile = { workspace = true }
econbox-tilemap = { workspace = true }
econbox-tileview = { workspace = true }

[features]
default = ["dev"]
dev = ["bevy/bevy_dev_tools"]
fast-link = ["bevy/dynamic_linking"]

[lints]
workspace = true
